=== al2wyw/jaxws/spring_jaxws/src/People.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.myws.com/"
xmlns="http://www.myws.com/"
 elementFormDefault="qualified">

 	<xs:complexType name="Person_Type">
   <xs:sequence>
    <xs:element name="name" type="xs:string" />
    <xs:element name="id" type="xs:string" />
    <xs:element name="salary" type="xs:decimal" />
   </xs:sequence>
   <xs:attribute name="male" type="xs:string"/>
  </xs:complexType>

 <xs:element name="People">
 	<xs:complexType>
 		<xs:sequence>
 			<xs:element name="Person" type="Person_Type" maxOccurs="unbounded">
 			</xs:element>
 			<xs:element name="love" type="xs:string"></xs:element>
 			<xs:element name="test" type="xs:string"></xs:element>
 			<xs:element name="badlove">
 				 <xs:complexType>
    				<xs:simpleContent>
      					<xs:extension base="xs:string">
        					<xs:attribute name="person" type="xs:string" use="required"/>
        					<xs:attribute name="action" type="xs:string" use="required"/>
     					 </xs:extension>
    				</xs:simpleContent>
  				</xs:complexType>
 			</xs:element>
 		</xs:sequence>  
 	</xs:complexType>
 </xs:element>
 
</xs:schema>

=== al2wyw/jaxws/spring_jaxws/src/People.xml
<People xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.myws.com/"
xsi:schemaLocation="http://www.myws.com/ People.xsd">
	<Person>
		<name>Peter</name>
		<id>abc345</id>
		<salary>1189.34</salary>
	</Person>
	<Person>
		<name>Anne</name>
		<id>abd345</id>
		<salary>189.12</salary>
	</Person>
	<Person male="test">
		<name>Ken</name>
		<id>abe545</id>
		<salary>89.12</salary>
	</Person>
	<Person>
		<name>Sue</name>
		<id>abf345</id>
		<salary>89.34</salary>
	</Person>
	<love>test</love>
	<test/>
	<badlove person="peter" action="beat">test</badlove>
	<att attr="test"/>
</People>
